### ISSUE TITLE
[Bug] No such method error

### ISSUE THREAD

**Issue by gamerover98** [Despical/CommandFramework#8]
## Description of Issue
When the command is unloaded, a `java.lang.NoSuchMethodError: org.bukkit.command.CommandMap.getKnownCommands()` is thrown.

## Steps to Reproduce
Just call `commandFramework.unregisterCommands()`

## Command Framework Version
1.2.3

## Server Version
The issue occurs from Spigot 1.8.8 to 1.11.2.
From 1.12 the `unregisterCommands()` method works fine.

## Stack Trace/Log
```
Error occurred while disabling CustomPlugin v1.0.0 (Is it up to date?)
java.lang.NoSuchMethodError: org.bukkit.command.CommandMap.getKnownCommands()Ljava/util/Map;
	at me.despical.commandframework.CommandFramework.lambda$unregisterCommand$2(CommandFramework.java:217)
```

**Comment by Despical** [comment]
I think some reflection is needed for legacy versions, thanks again.
